name: gradle-ci

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2.5.0
      with:
        java-version: '17'
        distribution: 'temurin'
        java-package: 'jdk'
    - name: Make gradle executable
      run: chmod +x gradlew
    - name: Build artifacts
      run: ./gradlew shadowJar
    
    - name: Deploy Artifacts
      env:
        DEPLOY_CREDS: ${{ secrets.DEPLOY_CREDS }}
      shell: bash
      run: |
        echo ${DEPLOY_CREDS} > gradle.properties
        ./gradlew publish
